project:
  type: website
  output-dir: docs
render:
      - index.qmd
      - MOD1_Yquanti_001.qmd
      - MOD1_Yquanti_004.qmd
      - MOD1_Yquanti_002.qmd
      - MOD1_Yquanti_003.qmd
      - MOD1_Yquanti_005.qmd

website:
  title: "Mod√©lisation d'une variable quantitative"
  navbar:
    left:
      - MOD1_Yquanti_001.qmd
      - MOD1_Yquanti_004.qmd
      - MOD1_Yquanti_002.qmd
      - MOD1_Yquanti_003.qmd
      - MOD1_Yquanti_005.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



